name: minerva-py312
channels:
  - anaconda
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - expat=2.6.4
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.12.8
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - annotated-types==0.7.0
    - anthropic==0.42.0
    - anyio==4.7.0
    - beautifulsoup4==4.12.3
    - certifi==2024.12.14
    - charset-normalizer==3.4.0
    - click==8.1.8
    - distro==1.9.0
    - dnspython==2.7.0
    - frozendict==2.4.6
    - grpcio==1.67.1
    - h11==0.14.0
    - html5lib==1.1
    - httpcore==1.0.7
    - httpx==0.28.1
    - idna==3.10
    - iniconfig==2.0.0
    - jiter==0.8.2
    - lxml==5.3.0
    - milvus-lite==2.4.10
    - multitasking==0.0.11
    - numpy==2.2.0
    - openai==1.58.1
    - packaging==24.2
    - pandas==2.2.3
    - peewee==3.17.8
    - platformdirs==4.3.6
    - pluggy==1.5.0
    - protobuf==5.29.2
    - pydantic==2.10.4
    - pydantic-core==2.27.2
    - pymilvus==2.5.2
    - pymongo==4.10.1
    - pytest==8.3.4
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.0.1
    - pytz==2024.2
    - pyyaml==6.0.2
    - requests==2.32.3
    - six==1.17.0
    - sniffio==1.3.1
    - soupsieve==2.6
    - tenacity==9.0.0
    - tqdm==4.67.1
    - typing-extensions==4.12.2
    - tzdata==2024.2
    - ujson==5.10.0
    - urllib3==2.2.3
    - webencodings==0.5.1
    - yfinance==0.2.51
